public class lwcCSVUploaderController {
    @AuraEnabled
    public static List<Account> saveFile(String base64Data) {
        String data = JSON.deserializeUntyped(base64Data).toString();
        List<Account> lstCCToInsert = new List<Account>();
        List<String> lstCSVLines = data.split('\n');

        for (Integer i = 1; i < lstCSVLines.size(); i++) {
            Account acc = new Account();
            String csvLine = lstCSVLines[i];
            String prevLine = csvLine;
            Integer startIndex;
            Integer endIndex;

            while (csvLine.indexOf('"') > -1) {
                if (startIndex == null) {
                    startIndex = csvLine.indexOf('"');
                    csvLine = csvLine.substring(0, startIndex) + ':quotes:' + csvLine.substring(startIndex + 1, csvLine.length());
                } else {
                    if (endIndex == null) {
                        endIndex = csvLine.indexOf('"');
                        csvLine = csvLine.substring(0, endIndex) + ':quotes:' + csvLine.substring(endIndex + 1, csvLine.length());
                    }
                }

                if (startIndex != null && endIndex != null) {
                    String sub = csvLine.substring(startIndex, endIndex);
                    sub = sub.replaceAll(',', ':comma:');
                    csvLine = csvLine.substring(0, startIndex) + sub + csvLine.substring(endIndex, csvLine.length());
                    startIndex = null;
                    endIndex = null;
                }
            }

            List<String> csvRowData = new List<String>();
            for (String column : csvLine.split(',')) {
                column = column.replaceAll(':quotes:', '').replaceAll(':comma:', ',');
                csvRowData.add(column);
            }

            if (csvRowData.size() >= 3) {
                acc.Name = csvRowData[0];
                acc.Site = csvRowData[1];
                acc.AccountSource = csvRowData[2];
                lstCCToInsert.add(acc);
            }
        }

        insert lstCCToInsert;
        return [SELECT Id, Name, Site, AccountSource FROM Account WHERE CreatedDate >= TODAY];
    }
}
